os: osx
osx_image: xcode10.2
language: objective-c
rvm: 2.4.2  # pre-installed in image
env:
  - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
cache:
  - bundler
  - cocoapods

before_install:
  - (ruby --version)
  - wget https://s3.us-east-2.amazonaws.com/s3.rubymotion.com/RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update && motion repo

gemfile:
  - Gemfile

script: bundle exec rake spec