os: osx
osx_image: xcode9.1
language: objective-c
rvm: 2.4.2  # pre-installed in image
cache:
  - bundler
  - cocoapods

before_install:
  - (ruby --version)

script:
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
  - sudo motion repo
  - bundle install --gemfile=./Gemfile --jobs=3 --retry=3
  - bundle exec rake clean
  - bundle exec rake spec
