os: osx
osx_image: xcode10.2
language: objective-c
env:
  - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
cache:
  - bundler
  - cocoapods

before_install:
  - (ruby --version)
  - wget -O RubyMotion-TravisCI.pkg http://travisci.rubymotion.com/
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/
  - touch /Applications/Xcode.app/Contents/Frameworks/.swift-5-staged
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update && motion repo
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion

gemfile:
  - Gemfile

script: bundle exec rake spec